baseURL = "/"
title = "顧客提案をエンジニアリングするブログ"
author = "bidman"
languageCode = "ja"
DefaultContentLanguage = "ja"
enableInlineShortcodes = true
theme = "ananke"

SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true